apiVersion: v1
kind: Services
metadata:
  name: lb
  labels:
    app: lbs
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  ---
  apiVersion: v1
  kind: Pod
  metadata:
    name: nginxpod
    labels: 
      app: nginx
  spec:
    containers:
      - name: nginxcont
        image: nginx:latest
        ports:
          - containerPort: 80
