apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: podrs
  labels:
    app: podrset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginxpodrs
  template:
      metadata: 
        name: nginxpod
        labels:
          app: nginxpodrs
      spec:
        containers:
          - name: nginxcont
            image: nginx:latest
            ports:
              - containerPort: 80
