apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rset 
  labels:
    app: rset
spec:
  replicas: 3
  selector:
    matchlabels:
      app: nginxrpset
  template:
    metadata:
      name: nginxpod
      labels: 
        app: nginxrpset
    spec:
      containers: 
      - name: nginxcont
        image: nginx:latest
        ports:
        - containerPort: 80