apiVersion: v1
kind: ReplicationController
metadata:
  name: httpdrc 
  labels:
    app: httpdrco
spec:
  replicas: 4
  selector:
    app: httpd
  template:
    metadata:
      name: httpdpod
      labels:
        app: httpd
    spec:
      containers:
        - name: httpdcont
          image: httpd:latest
          ports:
            containerPort: 80