apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: httpdrepset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      name: httpdpod
      labels:
        app: httpd
    spec:
      containers:
        - name: httpdcont
          image: httpd:latest
          ports:
            - containerPort: 80