apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: repset 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata: 
      name: nginxcont
      labels: 
        app: nginx
    spec:
      containers:
        - name: nginxcontainer
          image: nginx:latest
          ports:
            - containerPort: 80
    