apiVersion: apps/v1
kind: Deployment 
metadata:
  name: tomcathpa
  labels:
    app: tomcat 
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: tomcat-pod-hpa 
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: tomcatpod
      labels:
        app: tomcat-pod-hpa
    spec:
      containers:
        - name: tomcatcont
          image: tomcat:latest
          ports:
            - containerPort: 80
              protocol: TCP 
          resources:
            requests:
              cpu: "150m"
              memory: "152Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myhpa
  labels:
    app: myhpanew
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tomcathpa 
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource: 
        name: cpu
        target:
          type: Utilization 
          averageUtilization: 50
    - type: Resource 
      resource:
        name: memory 
        target:
          type: Utilization
          averageUtilization: 70