apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    type: pod 
spec:
  volumes:
    - name: mypv
      persistentVolumeClaim:
        claimName: mypod-pvc
  containers:
    - name: nginxcont
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: "/var/www/html/"
          name: mypv
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: mypod-pvc 
  labels:
    app: mypod-pvc 
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    type: pv
spec:
  storageClassName: standard 
  volumeMode: Filesystem 
  accessModes: 
    - ReadWriteOnce 
  capacity:
    storage: 10Gi 
  persistentVolumeReclaimPolicy: Recycle
  mountPath:
    path: "/home/"