apiVersion: v1
kind: Pod 
metadata: 
  name: mypod 
  labels:
    type: pod 
spec:
  volumes:
    - name: myvol1
      persistentVolumeClaim: 
        claimName: pvc-v1 
  containers:
    - name: nginxcont
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: "/var/www/html/"
          name: myvol1 
---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: mypvc
  labels:
    type: pvc 
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: mypv 
  labels:
    type: pv
spec:
  storageClassName: standard 
  volumeMode: Filesystem 
  accessModes: 
    - ReadWriteOnce 
  capacity:
    storage: 10Gi 
  PersistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/home/"