apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nginx-pv 
  labels:
    type: pv
spec:
  storageClassName: standard  
  volumeMode: FileSystem
  accessModes:
    - ReadWriteOnce
  capacity:
      storage: 10Gi
  persistentVolumeReclaimPolicy: Recycle
  hostPath: 
    path: "/home/"  