apiVersion: v1
kind: Pod
metadata:
  name: nginxpod-pvc
  labels:
    app: mypod-pvc
spec:
  volumes:
    - name: myvol1
      persistentVolumeClaim:
        claimName: nginx-pvc 
  containers:
    - name: nginxcont
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: "/var/www/html/"
          name: myvol1