apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  labels:
    app: nginx-pvc
spec:
  storageClassName: standard
  volumeMode: FileSystem
  accessModes:
    -ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"