apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sstedb
  labels:
    app: ssetdb 
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: mysqldb1
  template:
    metadata:
      name: nginxpod
      labels:
        app: mysqldb1 
    spec:
      containers:
        - name: nginxcont
          image: nginx:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secretkey
                  key: my_key

