apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: dbstatefulset
  labels:
    app: sset 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mysqldbset
  template:
    metadata:
      name: mysqlpod
      labels:
        app: mysqldbset
    spec:
      containers:
        - name: mysqlcont
          image: mysql:latest
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"