apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: sset 
  labels:
    app: ssetdb
spec:
  replicas: 3
  selctor:
    matchLabels:
      app: mysqlsset
  template:
    metadata:
      name: mysqlpod
      labels:
        app: mysqlsset
    spec:
      containers:
        - name: mysqlcontainer
          image: mysql:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: mysqlsecretkey
                    key: my_pass
