apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: Stateset 
  labels:
    app: stateset 
spec:
  replicas: 5
  selector:
  matchLabels:
    app: mysqlset
  template:
    metadata:
      name: mysqlpod 
      labels:
        app: mysqlset 
    spec:
      containers:
        - name: mysqlcontainer
          image: mysql:latest
          ports:
            - containerport: 3306
              protocol: TCP
          env:
            - name: MYSQL_DB_PASSWORD
              value: "12345678"